global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gravitee-gateway
    metrics_path: /_node/metrics/prometheus
    static_configs:
      - targets:
          - gateway:18082