coffeehouse:
  external:
    menu-service:
      url: ${MENU_SERVICE_URL}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: coffee-order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: coffee-order-api
          issuer-uri: ${JWT_ISSUER_URI}
